data:
  dataset: uni
  same_origin: false
  complexity: "n"
  ubound_per_batch: 5_000
  max_batches: 50_000
  path:
    pepmd_train: ./dataset/PepMD/train
    pepmd_valid: ./dataset/PepMD/valid
    ani1x_train: ./dataset/ANI-1x/train
    ani1x_valid: ./dataset/ANI-1x/valid
    atlas_train: ./dataset/ATLAS/train
    atlas_valid: ./dataset/ATLAS/valid
    pcqm_train: ./dataset/pcqm4mv2/train
    pcqm_valid: ./dataset/pcqm4mv2/valid
    pdb_train: ./dataset/PDB/train
    pdb_valid: ./dataset/PDB/valid
    spf_train: ./dataset/spf/train
    spf_valid: ./dataset/spf/valid

training:
  lr: 0.0005
  loss_type: null
  warmup: 1_000
  max_epoch: 500
  grad_clip: 1.0
  batch_size: 5
  patience: 8
  save_topk: 5
  shuffle: true
  num_workers: 8
  save_dir: /path/to/ckpt/pretrain

model:
  ckpt: null
  model_type: ekernel
  hidden_dim: 256
  ffn_dim: 512
  rbf_dim: 64
  expand_embed_dim: 32
  heads: 8
  layers: 4
  cutoff_lower: 0.0
  cutoff_upper: 5.0
  cutoff_H: 3.5
  k_neighbors: 16
  s_eu: 0.2
  s_a: 0.04